---
apiVersion: v1
kind: List
items:
 - 
  apiVersion: v1
  kind: Pod
  metadata:
   labels:
    app: microservice-app-example
    service: todos-api
   name: todos-api
  spec:
   containers:
    - 
     env:
      - 
       name: JWT_SECRET
       value: myfancysecret
      - 
       name: TODO_API_PORT
       value: '8082'
      - 
       name: REDIS_HOST
       value: redis
      - 
       name: REDIS_PORT
       value: '6379'
     image: ibuziuk/todos-api
     name: todos-api
     ports:
      - 
       containerPort: 8082
     imagePullPolicy: Always
     restartPolicy: Always
     resources:
      limits:
       memory: 512Mi
 - 
  apiVersion: v1
  kind: Service
  metadata:
   labels:
    app: microservice-app-example
   name: todos-api
  spec:
   ports:
    - 
     port: 8082
   selector:
    service: todos-api